### ISSUE TITLE
Class agnostic mask-RCNN

### ISSUE THREAD

**Issue by tpostadjian** [fizyr/keras-maskrcnn#101]
The original Mask-RCNN paper mentions that class agnostic segmentation leads to same performances as class-specific masks.

In this implementation, is there any possibility to get this unique segmentation.
I would like to get the features that leads to this segmentation so as to cut-off the classification part and be able to deal with new classes by analysis over the features that leads to segmentation.

Thanks !

**Comment by hgaiser** [comment]
We don't expose it, but it should be possible. You will have to make some modifications in the generator to produce the right target data, then you can set `num_classes` to 1 [here](https://github.com/fizyr/keras-maskrcnn/blob/master/keras_maskrcnn/models/retinanet.py#L94).

Closing this as it is not an issue.

**Comment by tpostadjian** [comment]
Sorry to keep going, but if I got it right, what you suggests is to build a 1-class dataset ?
It would indeed expose only one segmentation (as there is only one class).
But how can different classes be separated if the 1-class Mask R-CNN model is trained without learning to separate classes ?
