### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_retinanet.utils.gpu

### ISSUE THREAD

**Issue by MHansy** [fizyr/keras-maskrcnn#111]
Hi Team
I am trying to train M-RCNN using Keras and RetinaNet as in the Keras founder's example. I installed retinanet package but this module isn't found.  What should I do?

**Comment by vcarpani** [comment]
Hi, did you install the latest version of keras retinanet from github?

**Comment by MHansy** [comment]
> 
> 
> Hi, did you install the latest version of keras retinanet from github?

What I have done is to install through this command   pip install keras-retinanet

If this is not the one, please share how to install it.

**Comment by MHansy** [comment]
> 
> 
> Hi, did you install the latest version of keras retinanet from github?

I have tried, now it is okay! before to close the issue please help me some information from the error below during the training process.


ValueError: invalid CSV annotations file: ..../annotations.csv: line 0: format should be 'img_file,x1,y1,x2,y2,class_name,mask_path' or 'img_file,,,,,'



For sure in my CSV annotations file is as: img_fle,x1,y1,x2,y2,class_name. Nothing mask_path' , therefore I would like to know is the mask neccesary?

**Comment by vcarpani** [comment]
If you are using maskrcnn the mask is necessary, if you want to train just on bounding box, you can use keras retinanet

**Comment by MHansy** [comment]
> necessary, if you want to train just on bounding box, you can use keras retinanet

Thank you for your reply.
