### ISSUE TITLE
ResNEt50 Model

### ISSUE THREAD

**Issue by pGit1** [fizyr/keras-maskrcnn#14]
Where do we download the trained ResNet50 model from? I can't execute the sample code as a result.

```
# adjust this to point to your downloaded/trained model
model_path = os.path.join('', 'snapshots', 'resnet50_coco_v0.1.0.h5')
```

But I don't know where to find this model and I don't see where in the documentation.

**Comment by pGit1** [comment]
I even tried this to no avail:

https://github.com/fizyr/keras-retinanet/releases

When I try to load one of these models after I download them all I get is this error:

OSError: Unable to open file (File signature not found)

**Comment by hgaiser** [comment]
Try downloading the mask-rcnn model instead?

**Comment by pGit1** [comment]
1. THANK YOU FOR THE PROMPT RESPONSE!!!! I really appreciate your help!

2. I just did that and downloaded from here: https://github.com/fizyr/keras-maskrcnn/releases and I still get the weird error from above

**Comment by de-vri-es** [comment]
It is rather difficult for us to help you based on the issue you made here.

Please:
1) Refrain from calling your issue "URGENT" or similar. This is an open source project and we'll do our best to reply promptly to people. We are not paid support though, and we're not responsible for whatever deadline you may be missing.
2) Clearly state your goal: what are you trying to do?
3) Clearly explain the steps you have taken to get to that goal. What commands did you execute? What files did you download?
4) Explain how these steps failed. Where possible include output from the command that failed.

If you don't, we can't help you.

**Comment by pGit1** [comment]
Ive changed the name of the issue and removed urgent. 

I am simply trying to run the example found here:

https://github.com/fizyr/keras-maskrcnn/blob/master/examples/ResNet50MaskRCNN.ipynb

and my code breaks on the second cell with the error: OSError: Unable to open file (File signature not found)

My goal is to use this pretrained model on my own data to see how well it works out of the box. I would then eventually want to finetune on my own data based on the pretrained model. I want to get the example working before I try the model on my own images and currently I cannot execute the example file. In the **second cell** when I go to execute it, I cannot load the Keras model that I downloaded from the paths I specified in the comments above. 

![image](https://user-images.githubusercontent.com/13975114/41626223-8f187a46-73e9-11e8-9dff-e0255fd4d56a.png)


I wonder if I am downloading the wrong model? Again, I just want the eaxample to work smoothly before moving to my own data.

**Comment by hgaiser** [comment]
How big is the model you downloaded? Could you try redownloading it? It
seems it is corrupt.

**Comment by pGit1** [comment]
@hgaiser 

I think you are right. I am using Curl to get the files and it doesnt appear to be working. All my files are only 4KB large...SMH

Looking into now.

**Comment by pGit1** [comment]
@hgaiser 

My original problem was definitely file corruption and I can verify that I download the correct model with wget as opposed to curl but for some reason the model will not load without crashing the kernel. I can't see how my system is so different from the one you are executing on, especially since mine has about 128GB of RAM. I know it is not a memory issue. Perhaps I have a jupyter notebook config issue....

I am closing this for now as my original problem was solved but I have no idea why I still can't run this simple demo without headaches.
