### ISSUE TITLE
Instance Segmentation Mode

### ISSUE THREAD

**Issue by pGit1** [fizyr/keras-maskrcnn#15]
Hi thank you for all of your help. I have successfully tested the example you provide in the code on my own data and it works REALLY well! 

Is there a way to get the output to be instance aware? I think there is I am just wondering if it means modifying the draw_mask function.

```
from keras_maskrcnn.utils.visualization import draw_mask
```

**Comment by hgaiser** [comment]
The output is already instance aware.

**Comment by pGit1** [comment]
Should have rephrased my question, it was worded poorly. What I am really asking is how to make masks belonging to different classes have different colors. I may have missed it in the README but could find any info in it.

**Comment by hgaiser** [comment]
Ah that is indeed a different question. You can use ,[this](https://github.com/fizyr/keras-maskrcnn/blob/master/keras_maskrcnn/utils/visualization.py#L13) argument for that.

**Comment by pGit1** [comment]
Thank you kind sir!!

**Comment by pGit1** [comment]
@hgaiser 

how do I ask just general questions about implementation. I dont have issues per say but I am wondering how the network actually tries to reproduce the mask ground truth from an array perspective. 

As an example in image classification I feed a raw (pre-procd) image into a network and it has a one-hot output that has the same dimension as the number of classes I have. I'm just wondering what the analog is for a ground truth Mask. Makes little sense to me right now!

**Comment by hgaiser** [comment]
I've just created a keras-maskrcnn slack channel on the keras-team slack. I
think that is a good location for questions like these.

**Comment by pGit1** [comment]
Thanks!

**Comment by pGit1** [comment]
Can you send me the URL for the channel?
