### ISSUE TITLE
Keypoint usage?

### ISSUE THREAD

**Issue by teaglin** [fizyr/keras-maskrcnn#16]
Can this be used for key point detection?

**Comment by vcarpani** [comment]
Key point detection is not implemented but it should be easy to do if you want to try it. 
You can read on the original paper how they did it:
"By viewing each keypoint as a one-hot binary mask, with minimal modification Mask R-CNN can be applied to detect instance-specific poses."

**Comment by hgaiser** [comment]
@vcarpani answered this question, so I'll close it.
