### ISSUE TITLE
How to train a model on my own datasets with pretrained resnet152 model?

### ISSUE THREAD

**Issue by JingangLang** [fizyr/keras-maskrcnn#17]
Thanks for your great codes! I want to train my own data with pretrained model when the backbone is resnet152. But I can not find the Corresponding model.May you give me some advice?Thank you!

**Comment by hgaiser** [comment]
We currently have only trained resnet50, as we have limited resources so we focus on just one backbone. If you've trained a resnet152 on COCO and would like to share it, hit me up on the #keras-maskrcnn Slack channel.

**Comment by JingangLang** [comment]
Okay.
