### ISSUE TITLE
How to train the model to detecte objects only?

### ISSUE THREAD

**Issue by JingangLang** [fizyr/keras-maskrcnn#18]
How can I close the branch used to Object Segmentation task?I only have images and the corresponding border and category information.Hence how to modify the codes to only detecte the objects?Thanks!

**Comment by vcarpani** [comment]
If you only want to detect objects, without segmentation, you can use our implementation of retinanet:
https://github.com/fizyr/keras-retinanet

**Comment by hgaiser** [comment]
Let's move this discussion to the [keras-retinanet slack channel](https://github.com/fizyr/keras-retinanet#discussions).

**Comment by JingangLang** [comment]
Okay.
