### ISSUE TITLE
Mask colors

### ISSUE THREAD

**Issue by alteest** [fizyr/keras-maskrcnn#19]
Just to clarify.
For my own dataset I should create csv file in valid format. It's clear.
But when I create mask pictures, should I use the same color for all mask of the same class?
For example:
for cow always red
for cat always blue
etc

Also if I have several cows on picture with some superposition, should I create masks with at least 1 pixel between two objects?

**Comment by vcarpani** [comment]
The masks should all be white (255) over black.
The distance between the mask is not a problem (there can be superposition), but you should create a mask that shows the visible part of the cow, not the part that's behind another cow.

**Comment by hgaiser** [comment]
Additionally, a mask annotation should only show 1 object. No more, no less.

**Comment by alteest** [comment]
Yes. Now I see, object should be related to row in csv file. Ok, it's clear.
And color of mask is not matter, because in different pictures background
can be different : white, black, red, etc

2018-07-02 17:13 GMT+05:00 Hans Gaiser <notifications@github.com>:

**Comment by vcarpani** [comment]
[This ](https://drive.google.com/open?id=1O2GcWaOd1Sm9iNQO78YbpnMuUrW3323v)is an example of mask).
You should have one like this for each object in the picture.

**Comment by vcarpani** [comment]
Closing this issue, it can continue on keras-maskrcnn channel on slack
