### ISSUE TITLE
CPU usage exceeding 60 GB when running model.predict on single image

### ISSUE THREAD

**Issue by ranti-iitg** [fizyr/keras-maskrcnn#20]
running this 
outputs = model.predict_on_batch(np.expand_dims(image, axis=0)), 
where model is 
resnet50_coco_v0.1.0.h5

on a GPU enabled device consumes  more than 60 GB of RAM, after that machine freezes.
1. Device is GPU enabled.
2. Batch size is 1.

**Comment by vcarpani** [comment]
Can you give us more information: how many classes (and their indices in class files), dimension of the images

**Comment by ranti-orbital** [comment]
I am just following this notebook with the same image. https://github.com/fizyr/keras-maskrcnn/blob/master/examples/ResNet50MaskRCNN.ipynb

**Comment by 404hasbeenfound** [comment]
@ranti-orbital hi, you are welcome, do you know how to run in linux without jupyternotebook?

**Comment by 404hasbeenfound** [comment]
@ranti-iitg  hi, you are welcome, do you know how to run in linux without jupyternotebook?

**Comment by hgaiser** [comment]
There was an inefficiency in the architecture, should be fixed by https://github.com/fizyr/keras-maskrcnn/pull/34

Could you try that to see if it resolves your issue?

**Comment by ranti-iitg** [comment]
@hgaiser yup it works, thanks
