### ISSUE TITLE
How to Predict on Batch of Images

### ISSUE THREAD

**Issue by raghavgurbaxani** [fizyr/keras-maskrcnn#21]
Hi

Thank you for the amazing work. Could you please specify how to do predictions on batches of images ?

**Comment by hgaiser** [comment]
That's currently not possible for keras-maskrcnn, not all layers support
this. Pull requests to fix this are of course welcome

**Comment by raghavgurbaxani** [comment]
@hgaiser  is it possible to get predictions on keras retinanet ?

Does the NMS layer not support batch size >1 ?

**Comment by hgaiser** [comment]
Sorry for the late reply, I seem to have missed this issue. On retinanet it is supported, it's in the maskrcnn specific layers where support is lacking.

**Comment by hgaiser** [comment]
Should be supported with https://github.com/fizyr/keras-maskrcnn/pull/72
