### ISSUE TITLE
Can you provide me with a CSV data format? just like retinanet

### ISSUE THREAD

**Issue by Wulingtian** [fizyr/keras-maskrcnn#22]
not mask, like this: /data/imgs/img_001.jpg,837,346,981,456,cow

**Comment by vcarpani** [comment]
Her's an example with two images:
data/imgs/img_001.png,363,109,840,504,cow,masks/img_001/mask_001.png
data/imgs/img_001.png,441,128,643,351,sheep,masks/img_001/mask_002.png
data/imgs/img_002.png,365,159,810,534,cow,masks/img_002/mask_001.png

**Comment by Wulingtian** [comment]
@vcarpani not mask, like this: /data/imgs/img_001.jpg,837,346,981,456,cow

**Comment by vcarpani** [comment]
If you do not need masks there i no reason for using maskrcnn instead of retinanet
