### ISSUE TITLE
TypeError: 'list' object cannot be interpreted as an integer when training on custom dataset

### ISSUE THREAD

**Issue by PhilippMarquardt** [fizyr/keras-maskrcnn#25]
Hi, I have a problem with the training on a custom dataset. I've downloaded the dataset from [Data Science Bowl 2018](https://www.kaggle.com/c/data-science-bowl-2018/data) and generated myself the requiered .csv for training your network.

**Example row of my annotations csv :** data/stage1train/00071198d059ba7f5914a526d124d28e6d010c92466da21d4a04cd5413362552/images/00071198d059ba7f5914a526d124d28e6d010c92466da21d4a04cd5413362552.png,46,180,64,200,nucleus,data/stage1train/00071198d059ba7f5914a526d124d28e6d010c92466da21d4a04cd5413362552/masks/07a9bf1d7594af2763c86e93f05d22c4d5181353c6d3ab30a345b908ffe5aadc.png

**The only row in my classes csv:**
nucleus,0

When I try to train your network like this:
%run -i keras_maskrcnn/bin/train.py csv annotations.csv classes.csv
in the notebook it starts of fine with showing me the architecture and loading model stuff, I see Epoch 1/50 and after that an **error**:

> TypeError                                 Traceback (most recent call last)
> ~\Source\Repos\Mask-RCNN\keras_maskrcnn\bin\train.py in <module>()
>     295 
>     296 if __name__ == '__main__':
> --> 297     main()
> 
> ~\Source\Repos\Mask-RCNN\keras_maskrcnn\bin\train.py in main(args)
>     291         verbose=1,
>     292         callbacks=callbacks,
> --> 293         max_queue_size=1,
>     294     )
>     295 
> 
> ~\Anaconda3\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
>      89                 warnings.warn('Update your `' + object_name +
>      90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
> ---> 91             return func(*args, **kwargs)
>      92         wrapper._original_function = func
>      93         return wrapper
> 
> ~\Anaconda3\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
>    1413             use_multiprocessing=use_multiprocessing,
>    1414             shuffle=shuffle,
> -> 1415             initial_epoch=initial_epoch)
>    1416 
>    1417     @interfaces.legacy_generator_methods_support
> 
> ~\Anaconda3\lib\site-packages\keras\engine\training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
>     175             batch_index = 0
>     176             while steps_done < steps_per_epoch:
> --> 177                 generator_output = next(output_generator)
>     178 
>     179                 if not hasattr(generator_output, '__len__'):
> 
> ~\Anaconda3\lib\site-packages\keras\utils\data_utils.py in get(self)
>     791             success, value = self.queue.get()
>     792             if not success:
> --> 793                 six.reraise(value.__class__, value, value.__traceback__)
> 
> ~\Anaconda3\lib\site-packages\six.py in reraise(tp, value, tb)
>     691             if value.__traceback__ is not tb:
>     692                 raise value.with_traceback(tb)
> --> 693             raise value
>     694         finally:
>     695             value = None
> 
> ~\Anaconda3\lib\site-packages\keras\utils\data_utils.py in _data_generator_task(self)
>     656                             # => Serialize calls to
>     657                             # infinite iterator/generator's next() function
> --> 658                             generator_output = next(self._generator)
>     659                             self.queue.put((True, generator_output))
>     660                         else:
> 
> ~\Source\Repos\Mask-RCNN\keras_maskrcnn\preprocessing\generator.py in __next__(self)
>     259 
>     260     def __next__(self):
> --> 261         return self.next()
>     262 
>     263     def next(self):
> 
> ~\Source\Repos\Mask-RCNN\keras_maskrcnn\preprocessing\generator.py in next(self)
>     270             self.group_index = (self.group_index + 1) % len(self.groups)
>     271 
> --> 272         return self.compute_input_output(group)
> 
> ~\Source\Repos\Mask-RCNN\keras_maskrcnn\preprocessing\generator.py in compute_input_output(self, group)
>     254 
>     255         # compute network targets
> --> 256         targets = self.compute_targets(image_group, annotations_group, masks_group)
>     257 
>     258         return inputs, targets
> 
> ~\Source\Repos\Mask-RCNN\keras_maskrcnn\preprocessing\generator.py in compute_targets(self, image_group, annotations_group, masks_group)
>     217             image_group,
>     218             annotations_group,
> --> 219             self.num_classes()
>     220         )
>     221 
> 
> ~\AppData\Roaming\Python\Python36\site-packages\keras_retinanet\utils\anchors.py in anchor_targets_bbox(anchors, annotations, num_classes, mask_shape, negative_overlap, positive_overlap, **kwargs)
>      46     # anchor states: 1 is positive, 0 is negative, -1 is dont care
>      47     anchor_states = np.zeros((anchors.shape[0],))
> ---> 48     labels        = np.zeros((anchors.shape[0], num_classes))
>      49 
>      50     if annotations.shape[0]:
> 
> TypeError: 'list' object cannot be interpreted as an integer

I failed to find my error. Any help is appreciated! 
(btw running keras 2.2.2)

**Comment by hgaiser** [comment]
Can you try updating both retinanet and maskrcnn and try again?

**Comment by PhilippMarquardt** [comment]
It does work now! The pip install stuff for the keras_retinanet didn't really work though. It was always missing the utils.config.py file. I downloaded the newest version of your keras-retinanet repo and copied the files. Now it is working.

**Comment by hgaiser** [comment]
Awesome ! :)
