### ISSUE TITLE
there is a issue when i want to run the example, ‘No module named 'keras_maskrcnn'‘，what can i do for this?

### ISSUE THREAD

**Issue by 404hasbeenfound** [fizyr/keras-maskrcnn#33]

**Comment by hgaiser** [comment]
You either need to install the package or let python know how to find it. I assume you're using jupyter notebook, so that'd be something along the lines of:
```shell
PYTHONPATH=/path/to/keras-maskrcnn jupyter-notebook
```

**Comment by bhanuteja2001** [comment]
Hi im having the same problem.
Im trying on colab.
@hgaiser can u please tell how to give path in jupyter notebook.
