### ISSUE TITLE
ResNet50MaskRCNN doesn't appear to be notebook

### ISSUE THREAD

**Issue by monjha** [fizyr/keras-maskrcnn#36]
Hello,

It seems like there is an issue while opening this ResNet50MaskRCNN file. Could you please push this file to git again?

Thanks!

**Comment by petetakacs** [comment]
Hi,

Same error here:

Unreadable Notebook: /keras-maskrcnn/examples/ResNet50MaskRCNN.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)
