### ISSUE TITLE
How to get the coordinates of the mask generated

### ISSUE THREAD

**Issue by nirajvermafcb** [fizyr/keras-maskrcnn#42]
I was successfully able to train the model on my own dataset.But I want to get the coordinates of the mask generated

**Comment by hgaiser** [comment]
The coordinates can be found in the detected bounding box.

**Comment by nirajvermafcb** [comment]
Is there a way to get the coordinates of the mask generated ?

**Comment by hgaiser** [comment]
Check the example and related code in this repository for how to map the mask output to your image.

https://github.com/fizyr/keras-maskrcnn/blob/master/examples/ResNet50MaskRCNN.ipynb
