### ISSUE TITLE
Getting masks polygon points with respect to image shape

### ISSUE THREAD

**Issue by nirajvermafcb** [fizyr/keras-maskrcnn#44]
I have trained the model on two classes and my masks shape is [100,28,28,2].I want to know what does the 4 dimension here represents and how can I get the masks polygon points.

**Comment by hgaiser** [comment]
Again, check our [visualization](https://github.com/fizyr/keras-maskrcnn/blob/master/keras_maskrcnn/utils/visualization.py#L22-L29) function to see how we map a mask back to the image.

Regarding the shape, it is `(num_detections, mask_height, mask_width, num_classes)`.

Closing this as it is not an issue with the code. Please use the Slack channel for further discussions.
