### ISSUE TITLE
How to resume training from saved snapshots

### ISSUE THREAD

**Issue by nirajvermafcb** [fizyr/keras-maskrcnn#46]
I am able to train the model by using the command 
**python train.py csv training/annotations.csv training/classes.csv**   which by default starts from IMage net weights. Now if I want to resume the training from my own weights which is getting saved in the snapshots folder I am confused how should I pass that parameter via command line.

Right now I am using this:

 **python train.py csv training/annotations.csv training/classes.csv --weights=snapshots/r
esnet50_csv_02.h5**

But I am getting this message:

usage: train.py [-h]
                [--snapshot SNAPSHOT | --imagenet-weights | --weights WEIGHTS | --no-weights]
                [--backbone BACKBONE] [--batch-size BATCH_SIZE] [--gpu GPU]
                [--epochs EPOCHS] [--steps STEPS]
                [--snapshot-path SNAPSHOT_PATH]
                [--tensorboard-dir TENSORBOARD_DIR] [--no-snapshots]
                [--no-evaluation] [--freeze-backbone]
                [--no-class-specific-filter] [--config CONFIG]
                [--weighted-average]
                {coco,csv} ...
Can you explain how can I pass mutually exclusive group arguments.Thanks!

**Comment by hgaiser** [comment]
Every argument after your dataset is parsed by the dataset parser, but the weights are not part of that argument list. The weights should be passed **before** the dataset arguments.

**Comment by OllieLollie1** [comment]
This is related so I thought it would be best not to open a new issue.
How can you start from the pretrained network and add classes to the network?
