### ISSUE TITLE
Mask per instace or mask per class?

### ISSUE THREAD

**Issue by MichaelMonashev** [fizyr/keras-maskrcnn#53]
I generate synthetic dataset and try to train on it. I found example:
```
/data/imgs/img_001.jpg,837,346,981,456,cow,/data/masks/img_001_001.png
/data/imgs/img_002.jpg,215,312,279,391,cat,/data/masks/img_002_001.png
/data/imgs/img_002.jpg,22,5,89,84,bird,/data/masks/img_002_002.png
/data/imgs/img_003.jpg,,,,,,
``` 
/data/masks/img_001_001.png - is it mask for **all** cows on /data/imgs/img_001.jpg , or it containing mask for only **one** cow located inside bbox(837,346,981,456) ?

**Comment by vcarpani** [comment]
It is the mask only for one cow located inside the bounding box
