### ISSUE TITLE
Faster retraining with new classes.

### ISSUE THREAD

**Issue by MichaelMonashev** [fizyr/keras-maskrcnn#54]
How to add more classes to predict without retraining whole network from ImageNet weights? May be it will be useful to save backbone, regression, classification and mask subnet weights separately.

**Comment by hgaiser** [comment]
Currently if you retrain from the COCO weights it will copy most weights, regardless of the number of classes. The only weights not copied: classification submodel in retinanet and mask estimation in maskrcnn. Without assuming anything about the classes, this is the easiest / simplest approach while still copying a lot of weights.
