### ISSUE TITLE
To train on multiple gpus

### ISSUE THREAD

**Issue by nirajvermafcb** [fizyr/keras-maskrcnn#60]
How to train the model using multiple gpus in parallel

**Comment by nirajvermafcb** [comment]
But in train.py there is command line argument for batch size. What does that refer to?

**Comment by hgaiser** [comment]
It's already there in case we support it in the layers in the future :)

**Comment by jyning12** [comment]
so the model can not be trained with GPU, it will be very slow

**Comment by hgaiser** [comment]
Batch size > 1 is now supported, so this should be fixed.
