### ISSUE TITLE
one mask per image

### ISSUE THREAD

**Issue by hghari** [fizyr/keras-maskrcnn#64]
hi, I have lots of objects in one image is that possible to use only one mask for each image. this way all the objects in the image will have same mask but different bounding boxes, thanks

**Comment by vcarpani** [comment]
In theory it should be possible, in practice I would not recommend do it, since objects may have overlapping bounding boxes, but not overlapping masks.

**Comment by hgaiser** [comment]
As @vcarpani said, it would be possible but if you use the same value as foreground in your one mask (255 for instance) then you can't distinguish two neighboring objects from each other. Their bounding box could include part of the other objects' mask. You could work around this by using different values for the masks, so for instance object 1 has pixel value 1 in the mask, object 2 has pixel value 2.

Regardless, you'd need to write your own data generator to handle this situation, we don't support it. As this is not an issue with the code, I'm closing it.
