### ISSUE TITLE
the 'masks'files in csv's data is empty or not empty.

### ISSUE THREAD

**Issue by Zweiyuan** [fizyr/keras-maskrcnn#69]
My file about  data like this:
> --csv
> &nbsp;&nbsp;&nbsp;&nbsp;--JPEGImages
>  &nbsp;&nbsp;&nbsp;&nbsp;--masks
>  &nbsp;&nbsp;&nbsp;&nbsp;--annotations.csv
>  &nbsp;&nbsp;&nbsp;&nbsp;--classes.csv

the 'JPEGImages' includes pictures.  
but, should the 'masks'file is empty? Are those ‘mask.png’ generated automatically?
 
If the 'masks'file is empty. There is the issue about [this](https://github.com/fizyr/keras-maskrcnn/issues/67)

**Comment by hgaiser** [comment]
Your dataset needs to contain the images, the bounding boxes and the masks.
