### ISSUE TITLE
Can keras-maskrcnn training/inference work without the mask image annotation?

### ISSUE THREAD

**Issue by liminghuiv** [fizyr/keras-maskrcnn#73]
I am interested in running the keras-maskrcnn with keras-retinanet mainly to detect bounding box. papers reported that retinanet with roialign get better MAP (~1-2% performance improvement).
In the readme, for the csv based training, it needs the mask image for the annotated object, can this part be optional? then it will be exactly what I mentioned.

Thanks and best regards,

Liming

**Comment by hgaiser** [comment]
Retinanet is a single-stage object detector, introducing ROI Align will make it a two-stage object detector. Basically, that is what FasterRCNN does. Which paper reports that Retinanet with ROIAlign gets better mAP?

If you're only interested in bounding boxes, check [keras-retinanet](https://github.com/fizyr/keras-retinanet).

**Comment by liminghuiv** [comment]
> Retinanet is a single-stage object detector, introducing ROI Align will make it a two-stage object detector. Basically, that is what FasterRCNN does. Which paper reports that Retinanet with ROIAlign gets better mAP?
> 
> If you're only interested in bounding boxes, check [keras-retinanet](https://github.com/fizyr/keras-retinanet).
This blog post reported:
The ROI align is reported to have ~3 points improvement in AP in trainval35k.
https://medium.com/@steve101777/roi-pooling-and-roi-align-dd13bfece1df

Thanks a lot.
Liming
