### ISSUE TITLE
    boxes  = outputs[-4][0]

### ISSUE THREAD

**Issue by tuboxin** [fizyr/keras-maskrcnn#79]
processing time:  4.778490304946899
Traceback (most recent call last):
  File "F:/python/keras-maskrcnn-master/ResNet50MaskRCNN.py", line 54, in <module>
    boxes  = outputs[-4][0]
IndexError: list index out of range

**Comment by hgaiser** [comment]
What does the file `ResNet50MaskRCNN.py` do? What model did you use? What version of tensorflow / keras / keras-retinanet / keras-maskrcnn do you use?

**Comment by tuboxin** [comment]
> What does the file `ResNet50MaskRCNN.py` do? What model did you use? What version of tensorflow / keras / keras-retinanet / keras-maskrcnn do you use?

hello, I resolved it! thks anymore!

**Comment by zydx214737** [comment]
> processing time:  4.778490304946899
> Traceback (most recent call last):
> File "F:/python/keras-maskrcnn-master/ResNet50MaskRCNN.py", line 54, in 
> boxes  = outputs[-4][0]
> IndexError: list index out of range

**Comment by nadthoob** [comment]
I got the same error when running keras-maskrcnn/examples/ResNet50MaskRCNN.ipynb. I am using tensorflow 1.13.1. I am assuming that this has to do with a version problem related to one of the dependencies. My colleague got the same error separately on a different computer after we both set up new conda environments during the same time period. I can't find any help with this error anywhere.

processing time:  6.560770273208618
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-31-9d8a7fb554e0> in <module>
     16 print("processing time: ", time.time() - start)
     17 
---> 18 boxes  = outputs[-4][0]
     19 scores = outputs[-3][0]
     20 labels = outputs[-2][0]

IndexError: list index out of range

My conda environment:
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu
absl-py                   0.8.0                    py37_0
asn1crypto                1.0.1                    py37_0    conda-forge
astor                     0.8.0                    py37_0
astroid                   2.3.1                    py37_0    conda-forge
astropy                   3.2.2            py37hfa6e2cd_0    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl
bleach                    3.1.0                      py_0    conda-forge
ca-certificates           2019.8.28                     0
certifi                   2019.9.11                py37_0
cffi                      1.12.3           py37hb32ad35_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
colorama                  0.4.1                      py_0    conda-forge
confuse                   1.0.0                      py_0    conda-forge
cryptography              2.7              py37hb32ad35_0    conda-forge
cudatoolkit               10.0.130                      0
cudnn                     7.6.0                cuda10.0_0
cycler                    0.10.0                   py37_0
cython                    0.29.13                  pypi_0    pypi
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
freetype                  2.9.1                ha9979f8_1
gast                      0.3.2                      py_0
git                       2.20.1               h6bb4b03_0
grpcio                    1.16.1           py37h351948d_1
h5py                      2.9.0            py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
htmlmin                   0.1.12                     py_1    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                   py37_1000    conda-forge
importlib_metadata        0.23                     py37_0    conda-forge
intel-openmp              2019.4                      245
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.21                   py37_0    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
joblib                    0.13.2                   py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.0.2                    py37_0    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
keras-applications        1.0.8                      py_0
keras-base                2.2.4                    py37_0
keras-gpu                 2.2.4                         0
keras-maskrcnn            0.2.2                    pypi_0    pypi
keras-preprocessing       1.1.0                      py_1
keras-resnet              0.2.0                    pypi_0    pypi
keras-retinanet           0.5.1                    pypi_0    pypi
kiwisolver                1.1.0            py37ha925a31_0
lazy-object-proxy         1.4.2            py37hfa6e2cd_0    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libopencv                 3.4.2                h20b85fd_0
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.9.2                h7bd577a_0
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libtiff                   4.0.10               hb898794_2
libxml2                   2.9.9                h9ce36c8_5    conda-forge
libxslt                   1.1.33               heafd4d3_0    conda-forge
llvmlite                  0.29.0           py37ha925a31_0
lxml                      4.4.1            py37heafd4d3_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.1.1                    py37_0
markupsafe                1.1.1            py37hfa6e2cd_0    conda-forge
matplotlib                3.1.1            py37hc8f65d3_0
mccabe                    0.6.1                      py_1    conda-forge
missingno                 0.4.2                      py_0    conda-forge
mistune                   0.8.4           py37hfa6e2cd_1000    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.14           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
mock                      3.0.5                    py37_0
more-itertools            7.2.0                      py_0    conda-forge
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.0                    py37_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
numba                     0.45.1           py37hf9181ef_0
numpy                     1.16.5           py37h19fb1c0_0
numpy-base                1.16.5           py37hc3f5095_0
olefile                   0.46                     py37_0
opencv-python             4.1.1.26                 pypi_0    pypi
openssl                   1.1.1d               he774522_2
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.1           py37ha925a31_0
pandas-profiling          2.3.0                      py_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
patsy                     0.5.1                    py37_0
phik                      0.9.8                      py_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.2.0            py37hdc69c19_0
pip                       19.2.3                   py37_0
pluggy                    0.13.0                   py37_0    conda-forge
progressbar2              3.47.0                   pypi_0    pypi
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
protobuf                  3.9.2            py37h33f27b4_0
psutil                    5.6.3            py37hfa6e2cd_0    conda-forge
py                        1.8.0                      py_0    conda-forge
py-opencv                 3.4.2            py37hc319ecb_0
pycparser                 2.19                     py37_1    conda-forge
pydocstyle                4.0.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pylint                    2.4.2                    py37_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.2                      py_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.15.4           py37hfa6e2cd_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pytest                    5.2.1                    py37_0    conda-forge
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.5.0                      py_0    conda-forge
pytest-doctestplus        0.4.0                      py_0    conda-forge
pytest-openfiles          0.4.0                      py_0    conda-forge
pytest-pylint             0.14.1                     py_0    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
pytest-runner             5.1                        py_0    conda-forge
python                    3.7.4                h5263a28_0
python-dateutil           2.8.0                    py37_0
python-utils              2.3.0                    pypi_0    pypi
pytz                      2019.3                     py_0
pywin32                   224             py37hfa6e2cd_1000    conda-forge
pywinpty                  0.5.5                 py37_1000    conda-forge
pyyaml                    5.1.2            py37he774522_0
pyzmq                     18.1.0           py37h16f9016_0    conda-forge
qt                        5.9.7            vc14h73c81de_0
requests                  2.22.0                   py37_1    conda-forge
scikit-learn              0.21.3           py37h6288b17_0
scipy                     1.3.1            py37h29ff71c_0
seaborn                   0.9.0                    py37_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.4.0                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
snowballstemmer           2.0.0                      py_0    conda-forge
sqlite                    3.30.0               he774522_0
statsmodels               0.10.1           py37h8c2d366_0
tbb                       2019.4               h74a9793_0
tensorboard               1.13.1           py37h33f27b4_0
tensorflow                1.13.1          gpu_py37h83e5d6a_0
tensorflow-base           1.13.1          gpu_py37h871c8ca_0
tensorflow-estimator      1.13.0                     py_0
tensorflow-gpu            1.13.1               h0d30ee6_0
termcolor                 1.1.0                    py37_1
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.8                hfa6e2cd_0
tornado                   6.0.3            py37he774522_0
traitlets                 4.3.3                    py37_0    conda-forge
urllib3                   1.25.6                   py37_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.16.0                     py_0
wheel                     0.33.6                   py37_0
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4    conda-forge
wrapt                     1.11.2           py37he774522_0
xlrd                      1.2.0                    py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.2                h6538335_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

**Comment by hgaiser** [comment]
Ah it could be that the example is outdated a bit. What is the length of `model.outputs`? I guess it's 3? Then the first index is boxes, second is labels and third is masks. If it works, feel free to make a PR to update it :)

**Comment by hgaiser** [comment]
I just checked the example with the provided COCO model and it seems to work as expected. What model are you using? Can you show the output of `print(model.outputs)`?
