### ISSUE TITLE
layers/upsample.py "resize_images" call is no longer compatible with keras-retinanet

### ISSUE THREAD

**Issue by joefriel** [fizyr/keras-maskrcnn#88]
keras-retinanet commit 7735bf1 changed "resize_images" to "resize" 

Replacing "resize_images" with "resize" in layers/upsample.py seems to fix it.

**Comment by hgaiser** [comment]
Yes, very perceptive, thank you! I renamed it back to `resize_images` in https://github.com/fizyr/keras-retinanet/commit/4af50f6f99d3a21896c641e99b02b1bcf676e336
