### ISSUE TITLE
Broadcast Error while evaluating 

### ISSUE THREAD

**Issue by RohitMidha23** [fizyr/keras-maskrcnn#94]
The model trains for 1 epoch but on validation set it gives the following error : 
`File "..\..\keras_maskrcnn\callbacks\coco.py", line 29, in on_epoch_end
    evaluate_coco(self.generator, self.model, self.threshold)`

  `File "..\..\keras_maskrcnn\utils\coco_eval.py", line 82, in evaluate_coco
    segmentation[b[1]:b[1] + b[3], b[0]:b[0] + b[2]] = mask`

`ValueError: could not broadcast input array from shape (1331,603) into shape (1330,603)`

**Comment by RohitMidha23** [comment]
For more clarity, if I have an image of size `(3024,4032,3)` the predicted mask is outside the image. 

The predicted mask has values `(1491: 1491 + 208, 3776: 3776 + 258)` which is `(1699,4034)`. 

Noticed this after printing the `x : xmax` and `y : ymax` values of the mask

**Comment by hgaiser** [comment]
Ah I think I see what causes this issue. It should be fixed with https://github.com/fizyr/keras-retinanet/commit/5524619f91699732ba24c6f52fb9e4b0b780b019 , could you try it?

**Comment by RohitMidha23** [comment]
@hgaiser yes it seems to be working now.

I'll let you know if I encounter that error again!
